/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fon.client.forms;

import com.fon.common.domain.Admin;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aleksa
 */
public class MainForm extends javax.swing.JFrame {

    Admin loggedAdmin;

    /**
     * Creates new form MainForm
     */
    public MainForm(Admin currentAdmin) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        this.loggedAdmin = currentAdmin;
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblFullnameTitle = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();
        lblFullname = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuSeminars = new javax.swing.JMenu();
        jMenuItemCreateSeminar = new javax.swing.JMenuItem();
        jMenuItemViewSeminars = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemCreateParticipant = new javax.swing.JMenuItem();
        jMenuItemViewParticipants = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemCreateSeminarSchedule = new javax.swing.JMenuItem();
        jMenuItemViewSeminarSchedules = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel.setText("Корисничко име:");

        lblFullnameTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFullnameTitle.setText("Добродошли у апликацију за устрој семинара, ");
        lblFullnameTitle.setToolTipText("");
        lblFullnameTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator.setForeground(java.awt.Color.black);

        lblFullname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jMenuSeminars.setText("Семинари");

        jMenuItemCreateSeminar.setText("Направи семинар");
        jMenuItemCreateSeminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateSeminarActionPerformed(evt);
            }
        });
        jMenuSeminars.add(jMenuItemCreateSeminar);

        jMenuItemViewSeminars.setText("Прегледај семинаре");
        jMenuItemViewSeminars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewSeminarsActionPerformed(evt);
            }
        });
        jMenuSeminars.add(jMenuItemViewSeminars);

        jMenuBar.add(jMenuSeminars);

        jMenu2.setText("Учесници");

        jMenuItemCreateParticipant.setText("Направи учесника");
        jMenuItemCreateParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateParticipantActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCreateParticipant);

        jMenuItemViewParticipants.setText("Прегледај учеснике");
        jMenuItemViewParticipants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewParticipantsActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemViewParticipants);

        jMenuBar.add(jMenu2);

        jMenu3.setText("Термини семинара");

        jMenuItemCreateSeminarSchedule.setText("Направи термин семинара");
        jMenuItemCreateSeminarSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateSeminarScheduleActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemCreateSeminarSchedule);

        jMenuItemViewSeminarSchedules.setText("Прегледај термине семинара");
        jMenuItemViewSeminarSchedules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewSeminarSchedulesActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemViewSeminarSchedules);

        jMenuBar.add(jMenu3);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(lblFullnameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblFullnameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCreateSeminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreateSeminarActionPerformed
        try {
            new ChangeSeminarForm(this, true, loggedAdmin, null).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemCreateSeminarActionPerformed

    private void jMenuItemViewSeminarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewSeminarsActionPerformed
        ViewSeminarsForm seminarSearchForm = new ViewSeminarsForm(this, true, loggedAdmin);
        seminarSearchForm.setVisible(true);
    }//GEN-LAST:event_jMenuItemViewSeminarsActionPerformed

    private void jMenuItemCreateParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreateParticipantActionPerformed
        try {
            CreateParticipantForm createParticipantForm = new CreateParticipantForm(this, true, loggedAdmin, null);
            createParticipantForm.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemCreateParticipantActionPerformed

    private void jMenuItemViewParticipantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewParticipantsActionPerformed
        ViewParticipantsForm searchParticipantForm = new ViewParticipantsForm(this, true);
        searchParticipantForm.setVisible(true);
    }//GEN-LAST:event_jMenuItemViewParticipantsActionPerformed

    private void jMenuItemCreateSeminarScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreateSeminarScheduleActionPerformed
        try {
            ChangeSeminarScheduleForm form = new ChangeSeminarScheduleForm(this, true, loggedAdmin, null);
            form.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemCreateSeminarScheduleActionPerformed

    private void jMenuItemViewSeminarSchedulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewSeminarSchedulesActionPerformed
        ViewSeminarSchedulesForm viewSeminarSchedulesForm = new ViewSeminarSchedulesForm(this, true, loggedAdmin);
        viewSeminarSchedulesForm.setVisible(true);
    }//GEN-LAST:event_jMenuItemViewSeminarSchedulesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCreateParticipant;
    private javax.swing.JMenuItem jMenuItemCreateSeminar;
    private javax.swing.JMenuItem jMenuItemCreateSeminarSchedule;
    private javax.swing.JMenuItem jMenuItemViewParticipants;
    private javax.swing.JMenuItem jMenuItemViewSeminarSchedules;
    private javax.swing.JMenuItem jMenuItemViewSeminars;
    private javax.swing.JMenu jMenuSeminars;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblFullnameTitle;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        lblFullname.setText(loggedAdmin.getFullName());
        lblUsername.setText(loggedAdmin.getUsername());
    }
}
